export const FORM_LIST = [
    [{
            label: "ドイツ語",
            keyName: "word",
            formType: "TextField",
            validate: /^[a-zA-ZäöüÄÖÜß]+$/,
        },
        {
            label: "意味",
            keyName: "meaning",
            formType: "TextField",
            validate: /^[^\x20-\x7e]+$/,
        },
        {
            label: "性",
            keyName: "distinction",
            data: ["男性", "女性", "中性"],
            formType: "SelectBox",
            validate: /^[^\x20-\x7e]+$/,
        },
        {
            label: "複数形",
            keyName: "plural",
            formType: "TextField",
            validate: /^[a-zA-ZäöüÄÖÜß!-/:-@¥[-`{-~]*$/,
        },
        {
            label: "日→独",
            keyName: "representative",
            data: [{label: "適用", value: true}, {label: "適用外", value: false}],
            formType: "RadioButton",
        },
    ],
    [{
            label: "ドイツ語",
            keyName: "word",
            formType: "TextField",
            validate: /^[a-zA-ZäöüÄÖÜß]+$/,
        },
        {
            label: "意味",
            keyName: "meaning",
            formType: "TextField",
            validate: /^[^\x20-\x7e]+$/,
        },
        {
            label: "種類",
            keyName: "distinction",
            data: ["一般動詞", "分離動詞", "非分離動詞", "助動詞"],
            formType: "SelectBox",
            validate: /^[^\x20-\x7e]+$/,
        },
        {
            label: "活用",
            keyName: "conjugationList",
            validate: /^[a-zA-ZäöüÄÖÜß]+$/,
        },
        {
            label: "日→独",
            keyName: "representative",
            data: [{label: "適用", value: true}, {label: "適用外", value: false}],
            formType: "RadioButton",
        },
    ],
    [{
            label: "ドイツ語",
            keyName: "word",
            formType: "TextField",
            validate: /^[a-zA-ZäöüÄÖÜß]+$/,
        },
        {
            label: "意味",
            keyName: "meaning",
            formType: "TextField",
            validate: /^[^\x20-\x7e]+$/,
        },
        {
            label: "種類",
            keyName: "distinction",
            data: ["一般動詞", "分離動詞", "非分離動詞", "助動詞"],
            formType: "SelectBox",
            validate: /^[^\x20-\x7e]+$/,
        },
        {
            label: "日→独",
            keyName: "representative",
            data: [{label: "適用", value: true}, {label: "適用外", value: false}],
            formType: "RadioButton",
        },
    ],
    [{
            label: "ドイツ語",
            keyName: "word",
            formType: "TextField",
            validate: /^[a-zA-ZäöüÄÖÜß]+$/,
        },
        {
            label: "意味",
            keyName: "meaning",
            formType: "TextField",
            validate: /^[^\x20-\x7e]+$/,
        },
        {
            label: "格支配",
            keyName: "case",
            data: ["２格", "３格", "４格", "３格か４格"],
            formType: "SelectBox",
            validate: /^[^\x20-\x7e]+$/,
        },
        {
            label: "日→独",
            keyName: "representative",
            data: [{label: "適用", value: true}, {label: "適用外", value: false}],
            formType: "RadioButton",
        },
    ],
    [{
            label: "ドイツ語",
            keyName: "word",
            formType: "TextField",
            validate: /^[a-zA-ZäöüÄÖÜß]+$/,
        },
        {
            label: "意味",
            keyName: "meaning",
            formType: "TextField",
            validate: /^[^\x20-\x7e]+$/,
        },
        {
            label: "種類",
            keyName: "distinction",
            data: ["並列", "副詞的", "従属的"],
            formType: "SelectBox",
            validate: /^[^\x20-\x7e]+$/,
        },
        {
            label: "日→独",
            keyName: "representative",
            data: [{label: "適用", value: true}, {label: "適用外", value: false}],
            formType: "RadioButton",
        },
    ],
];